### ISSUE TITLE
[UI-1] Splash Section

### ISSUE THREAD

**Issue by BlazingAsher** [hack-the-6ix/landing-2023#1]
Major requirements:
- [x] Design follows Figma specification
- [x] `We hack to ...` animated as given on Figma
- [x] Design is responsive: images are properly resized (no white background), content doesn't blend into background, all interactive elements are unobstructed
- [x] Email list sign up button should trigger a callback with email as parameter, which will be implemented later

Design reference (navbar implementation not needed for this ticket):
<img width="793" alt="image" src="https://user-images.githubusercontent.com/11510436/236644323-b3581d82-a1db-40a3-9824-faa69a5d0e4f.png">

**Comment by jeffrey-zang** [comment]
Input form should be transparent
![image](https://github.com/hack-the-6ix/landing-2023/assets/66485719/d67de969-328a-46f0-b01b-5ccc59c0fb09)

**Comment by jeffrey-zang** [comment]
No remaining issues, closing ticket
