### ISSUE TITLE
[UI-7] FAQ Section

### ISSUE THREAD

**Issue by BlazingAsher** [hack-the-6ix/landing-2023#7]
Major requirements:
- [x] Design follows Figma specification
- [x] Design is responsive: images are properly resized (no white background), content doesn't blend into background, all interactive elements are unobstructed
- [x] FAQ sections and content should be configurable using a JavaScript object (see past "Faq" for example)
- [x] When pressing the "+" icon, the question's answer should expand, like an accordion (same behaviour as last year)
- [x] On mobile, sections should be stacked, with one column instead of two

Design reference:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/11510436/236645181-0017e7cf-1414-4488-8d89-52bbbc0cca2b.png">

**Comment by jeffrey-zang** [comment]
Extra padding causing white space on mobile
![image](https://github.com/hack-the-6ix/landing-2023/assets/66485719/f0470d4b-1fef-423b-a10d-2085511513a3)

**Comment by jeffrey-zang** [comment]
Fixed in 5b8abd997148dc3f6afe5fc6b1087d3f335c9009
