### ISSUE TITLE
[UI-9] Footer

### ISSUE THREAD

**Issue by BlazingAsher** [hack-the-6ix/landing-2023#9]
Major requirements:
- [ ] Design follows Figma specification
- [ ] Design is responsive: images are properly resized (no white background), content doesn't blend into background, all interactive elements are unobstructed
- [ ] On mobile, the left hand side (name and copyright) should be on top of the links

Design reference:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/11510436/236645318-5dbcf43d-0e8c-4d03-acae-01069dd05e5b.png">

**Comment by jeffrey-zang** [comment]
Resolved in 0244b82
